packages:
  - "packages/*"

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - "agent-install"
  - "vite-plus"
  - "@voidzero-dev/*"
  - "oxlint"
  - "@oxlint/*"
  - "oxlint-tsgolint"
  - "@oxlint-tsgolint/*"
  - "oxfmt"
  - "@oxfmt/*"
  - "vitest"
  - "@vitest/*"
  - "@oxc-project/types"
  - "@oxc-project/runtime"
trustPolicy: no-downgrade
blockExoticSubdeps: true

overrides:
  vite@*: "catalog:"
  vitest@*: "catalog:"

trustPolicyExclude:
  - "vite-plus"
  - "@voidzero-dev/*"
  - "semver"
onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - esbuild
  - unrs-resolver
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
  vitest: 4.1.11
  vite-plus: 0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
